homefood/food/urls.py
from django.urls import path,include
from . import views

from rest_framework import routers

from food.views import ItemViewSet,ItemVgeViewSet,ItemSelectViewSet

from django.conf import settings
from django.conf.urls.static import static

router=routers.DefaultRouter()
router.register('item',ItemViewSet)
router.register('veg',ItemVgeViewSet)











# This is help to  hard coded name use app_name concept
app_name='food'
urlpatterns = [
    
    # food
    path('', views.foodlist,name='index'),
    # food/1
    path('<int:item_id>/',views.detail,name='detail'),
    # add item
    path('add',views.CreateItem.as_view(),name='create_item'),
    # Edit item
    path('update/<int:id>',views.update_item,name='update_item'),
    #delete item
    path('delete/<int:id>',views.delete_item,name='delete_item'),
    #REST
    path('rest',include(router.urls)),
   # path('rest/(?P<name>.+)',views.ItemSelectViewSet.as_view()),
   path('<name>/',views.type_list,name='item_name')

       
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homefood/homefood/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as auth_views 

from django.conf import settings
from django.conf.urls.static import static
app_name='homefood'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('register/',user_views.register,name="register"),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
]



urlpatterns  += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


homefood/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.

class Item(models.Model):
     def __str__(self):
          return self.Item_name
     user_name=models.ForeignKey(User,on_delete=models.CASCADE,default=1)
     Item_name= models.CharField(max_length=200)
     Item_desc= models.CharField(max_length=300)
     Item_price= models.IntegerField()
     Item_image= models.CharField(max_length=500,default="https://www.google.com/url?sa=i&url=http%3A%2F%2Fchaysendo.com%2Fthuc-uong-162&psig=AOvVaw0svv7irjRzq-nhIkbJkkUz&ust=1589142336011000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCMiFn9XOp-kCFQAAAAAdAAAAABAI")
     Item_Type=models.CharField(max_length=50, default='Veg')
     def get_absolute_url(self):
          return reverse("food:detail",kwargs={"item_id":self.pk})  

homefood/users/models.py
from django.db import models
from django.contrib.auth.models import User

class profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location=models.CharField(max_length=100)
    Acoount=models.IntegerField(default=0)
    
    
    def __str__(self):
           return self.user.username



# Create your models here.
    

homefood/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['Item_name','Item_desc','Item_price','Item_image']

homefood/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms  import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username','email','password1','password2']


homefood/food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from rest_framework import viewsets,generics
from .serializers import ItemSeri
from django.core.paginator import Paginator
from rest_framework.decorators import api_view
from rest_framework.response import Response


@api_view(['GET'])
def type_list(request,name):
    if request.method == 'GET':
        itemlist=Item.objects.all()
        itemlist=itemlist.filter(Item_Type=name)
        serializer = ItemSeri(itemlist, many=True)
        return Response(serializer.data)


class ItemViewSet(viewsets.ModelViewSet):
    queryset = Item.objects.all()
    serializer_class =  ItemSeri


class ItemVgeViewSet(viewsets.ModelViewSet):
      queryset = Item.objects.filter(Item_Type='Veg')
      serializer_class =  ItemSeri

class ItemSelectViewSet(generics.ListAPIView):
       serializer_class =  ItemSeri  
       def get_queryset(self):
           queryset = Item.objects.all()
           type_name=self.request.query_params.get('name',None)
           if type_name is not None:
               queryset = queryset.filter(Item_name=type_name)

           return  queryset



# Create your views here.
'''
def foodlist(request):
    itemlist=Item.objects.all()

    template=loader.get_template('food/index.html')
    context={
        'itemlist':itemlist,
    }
    return HttpResponse(template.render(context,request))
'''
#This is function based views

def foodlist(request):
     itemlist=Item.objects.all()
     item_name=request.GET.get('name')
     if item_name != '' and  item_name is not None :
         itemlist=itemlist.filter(Item_name__icontains=item_name)
     paginator=Paginator(itemlist,2)
     page = request.GET.get('page')

     
     itemlist=paginator.get_page(page)
     context={
         'itemlist':itemlist,
     }
     return render(request,'food/index.html',context)

#There is anoter way to replace above code using listview

# you can use listview insted function based view
class classfoodlist(ListView):
    model = Item
    template_name ='food/index.html'
    context_object_name ='itemlist'


def detail(request,item_id):
    item=Item.objects.get(pk=item_id)
    context = {

        'item':item,
    }
    return render(request,'food/detail.html',context)

def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request,'food/item-form.html',{ 'form':form })

    # This class based view for create item
class CreateItem(CreateView):
        model= Item
        fields=['Item_name','Item_desc','Item_price','Item_image','Item_Type']
        template_name='food/item-form.html'
        def form_valid(self,form):
            form.instance.user_name=self.request.user

            return super().form_valid(form)


def update_item(request,id):
    item=Item.objects.get(pk=id)
    form = ItemForm(request.POST or None,instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item-form.html',{ 'form':form, 'item':item })


def delete_item(request,id):
    item=Item.objects.get(pk=id)
    form = ItemForm(request.POST or None,instance=item)
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request,'food/delete-item.html',{'form':form,'item':item})
    

homefood/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterForm
from  django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):
    form = RegisterForm(request.POST)
    if form.is_valid():
        form.save()
        username=form.cleaned_data.get('username')
        messages.success(request,f'Welcome { username },your account is created')
        return redirect('food:index')
    else:
        form=RegisterForm()

    return render (request,'users/register.html',{'form':form})
@login_required
def profilepage(request):
    return render(request,'users/profile.html')

homefood/food/templates/food/base.html
{%  load static   %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
   <script defer src="{% static 'fontawesome/js/all.min.js' %}"></script>
   <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <title>Document</title>
</head>
<body>
    <script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    
       
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand"> MotherFood </a>
        <dev class="navbar">
<!-- this nav link create space between the every tab-->
            <a class="nav-item nav-link" href="{% url 'food:create_item' %}">Add Item</a>
            <a class="nav-item nav-link" href="{% url 'food:index' %}">Delete-Update Item</a>
           
            <a class="nav-item nav-link" href="#">Veiw Item</a>
            {%  if user.is_authenticated  %}
              <a href="{% url 'logout' %}" >Logout</a>
              <a href="{% url 'profile' %}">Profile</a>
              {% else %}
              <a href="{% url 'login' %}">Login</a>
              {% endif %}
        </dev>
    </nav>
    {% if messages %}
     {%  for message  in messages %}
     <div class="alert alert-{{ message.tags }}">
         {{ message }}

     </div>
      
     {% endfor %}
     {% endif %}

    {% block body %}
    {% endblock %}
</body>
</html>

homefood/food/templates/food/delete-item.html

{% extends 'food/base.html' %}
{% block body %}
<form method="POST">
{% csrf_token %}
<h2> Aru sure to delete this item {{ item.Item_name }}</h2>
<button type="submit">Conform</button>


</form> 

{% endblock %}

homefood/food/templates/food/detail.html
{% extends 'food/base.html' %}
 {% block body %}
 <dev class="container">
    <div class="row">
     <dev class="col-md-6">
         <img  class="card" hight="150px" width= "60%" src="{{ item.Item_image }}" class="card"/>
        
     </dev>
     <dev class="col-md-6">
        <h1> {{ item.Item_name }}</h1>
        <h2> {{ item.Item_desc }}</h2>
        <h3> ${{ item.Item_price }}</h3>     
       <a href="{% url 'food:delete_item' item.id %}">Delete</a>
       <a href="{% url 'food:update_item' item.id %}">update</a>
    </dev>
    </div>
 </dev>
 
 
 
 {% endblock %}

homefood/food/templates/food/index.html

{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
   
   
   
   
</head>
<body>
    
    {% block body %}

    <form action="" method="GET">
        <input type="search" name="name">
        <button type="submit">submit</button>
    </form>

    {% for item in itemlist %}
 
    
<div class="row">
    <div class="col-md-3 offset-md-2 ">
        <img    class="card" hight="150px" width= "90%" src="{{ item.Item_image }}" />

    </div>
    <div class="col-md-3">
        <h3> {{ item.Item_name }} </h3>
        <h3> {{ item.Item_desc }} </h3>
        <h3> ${{ item.Item_price }} </h3>

    </div>
    <div class="col-md-2">
        <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a> 

    </div>
</div>
  {% endfor %}

  {% if itemlist.has_previous  %}
  <a href="?page=1">First</a>
  <a href="?page={{ itemlist.previous_page_number }} ">Previous</a>
{% endif %}
Page: {{ itemlist.number }} of {{ itemlist.paginator.num_pages  }}
{% if itemlist.has_next %}
<a href="?page={{ itemlist.next_page_number }} ">Next</a>
<a href="?page={{ itemlist.paginator.num_pages }}">Last</a>
{% endif %}

    {% endblock %}
    
</body>
</html>

homefood/food/templates/food/item-form.html
{% extends 'food/base.html' %}



{% block body %}





<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4" >
            <div class="card">
                <div  class="card-header text-white bg-info">
                    <div class="card-title">ADD-ITEM</div>
                </div>
                <div class="card-body">
                   <form method="post" >
                      {% csrf_token %}
                      {%  for field in form  %}
                        <div class="form-group">
                           {{ field.name }}
                           <br>
                           {{ field }}
                           {% endfor %}
 
                        </div>
                      <button class="btn-info" type="submit">Save</button>
                   
                   </form>   
                </div>               
            </div>
        </div>
    </div>
 
 </div>















{% endblock %}

homefood/users/templates/users/login.html

{% extends 'food/base.html' %}
{% block body %}

<div class="container">
   <div class="row">
       <div class="col-md-4 offset-md-4" >
           <div class="card">
               <div  class="card-header text-white bg-info">
                   <div class="card-title">Login</div>
               </div>
               <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">{{ field.name }}
                        {{ field }}
                    </div>
                    
                    {% endfor %}
                    <button class="btn-info" type="submit">Login</button>
                    
                    </form>
               </div>               
           </div>
       </div>
   </div>

</div>





{%   endblock %}



homefood/users/templates/users/logout.html
<h1>You have been Log Out</h1>

<a href="{% url 'login' %}">Login</a>





homefood/users/templates/users/profile.html
<h1> {{ user.username }} </h1>
<img width="60px" hight="60px" src="{{ user.profile.image.url }}">
<h1>Acoount</h1><h1>{{ user.profile.Acoount }}</h1>

homefood/users/templates/users/register.html

{% extends 'food/base.html' %}
{% block body %}



<div class="container">
   <div class="row">
       <div class="col-md-4 offset-md-4" >
           <div class="card">
               <div  class="card-header text-white bg-info">
                   <div class="card-title">Register</div>
               </div>
               <div class="card-body">
                  <form method="post" >
                     {% csrf_token %}
                     {%  for field in form  %}
                       <div class="form-group">
                          {{ field.name }}
                          <br>
                          {{ field }}
                          {% endfor %}

                       </div>
                     <button class="btn-info" type="submit">Signup</button>
                  
                  </form>
               </div>               
           </div>
       </div>
   </div>

</div>


{% endblock %}




